steps:
    # Build the container image
    - name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "gcr.io/$PROJECT_ID/fnc-recon-api:$COMMIT_SHA", "."]
    # Push the container image to Container Registry
    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/$PROJECT_ID/fnc-recon-api:$COMMIT_SHA"]
    # Deploy container image to Cloud Run
    - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
      entrypoint: gcloud
      args:
          - "run"
          - "deploy"
          - "fnc-recon-api"
          - "--image"
          - "gcr.io/$PROJECT_ID/fnc-recon-api:$COMMIT_SHA"
          - "--region"
          - "us-east1"
      secretEnv: ['DB_NAME_SECRET', 'DB_PASS_SECRET', 'DB_USER_SECRET', 'INSTANCE_CONNECTION_NAME_SECRET']
images:
    - "gcr.io/$PROJECT_ID/fnc-recon-api:$COMMIT_SHA"
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/DB_NAME_SECRET/versions/1
    env: 'DB_NAME_SECRET'
  - versionName: projects/$PROJECT_ID/secrets/DB_PASS_SECRET/versions/1
    env: 'DB_PASS_SECRET'
  - versionName: projects/$PROJECT_ID/secrets/DB_USER_SECRET/versions/1
    env: 'DB_USER_SECRET'
  - versionName: projects/$PROJECT_ID/secrets/INSTANCE_CONNECTION_NAME_SECRET/versions/2
    env: 'INSTANCE_CONNECTION_NAME_SECRET'