# docker compose for local testing
version: '3.1'

services:
  api:
    container_name: fncreconapi
    build: .
    ports:
      - '${PORT}:${PORT}'
    expose:
      - '${PORT}'
    links:
      - db
  db:
    container_name: fncrecondb
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./test/db/init.sql:/docker-entrypoint-initdb.d/init.sql