CREATE DATABASE IF NOT EXISTS test;
USE test;
CREATE TABLE IF NOT EXISTS `reports` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `reporting_team` int unsigned NOT NULL,
  `year` int unsigned NOT NULL,
  `event` varchar(45) NOT NULL,
  `match` varchar(5) NOT NULL,
  `scouted_team` int unsigned NOT NULL,
  `alliance` varchar DEFAULT 'red1',
  `autonomous_game_pieces` in DEFAULT '0',
  `autonomous_game_pieces_missed` in DEFAULT '0',
  `auto_charging` varchar DEFAULT 'none',
  `high_cone_1` int DEFAULT '0',
  `high_cube_2` int DEFAULT '0',
  `high_cone_3` int DEFAULT '0',
  `high_cone_4` int DEFAULT '0',
  `high_cube_5` int DEFAULT '0',
  `high_cone_6` int DEFAULT '0',
  `high_cone_7` int DEFAULT '0',
  `high_cube_8` int DEFAULT '0',
  `high_cone_9` int DEFAULT '0',
  `mid_cone_1` int DEFAULT '0',
  `mid_cube_2` int DEFAULT '0',
  `mid_cone_3` int DEFAULT '0',
  `mid_cone_4` int DEFAULT '0',
  `mid_cube_5` int DEFAULT '0',
  `mid_cone_6` int DEFAULT '0',
  `mid_cone_7` int DEFAULT '0',
  `mid_cube_8` int DEFAULT '0',
  `mid_cone_9` int DEFAULT '0',
  `low_hybrid_1` int DEFAULT '0',
  `low_hybrid_2` int DEFAULT '0',
  `low_hybrid_3` int DEFAULT '0',
  `low_hybrid_4` int DEFAULT '0',
  `low_hybrid_5` int DEFAULT '0',
  `low_hybrid_6` int DEFAULT '0',
  `low_hybrid_7` int DEFAULT '0',
  `low_hybrid_8` int DEFAULT '0',
  `low_hybrid_9` int DEFAULT '0',
  `miss_cone_high` int DEFAULT '0',
  `miss_cone_mid` int DEFAULT '0',
  `miss_cone_low` int DEFAULT '0',
  `miss_cube_high` int DEFAULT '0',
  `miss_cube_mid` int DEFAULT '0',
  `miss_cube_low` int DEFAULT '0',
  `intake_single` int DEFAULT '0',
  `intake_double` int DEFAULT '0',
  `intake_floor` int DEFAULT '0',
  `intake_single_miss` int DEFAULT '0',
  `intake_double_miss` int DEFAULT '0',
  `intake_floor_miss` int DEFAULT '0',
  `endgame_charging` varchar DEFAULT 'none',
  PRIMARY KEY (`id`),
  KEY `unique_entry` (`year`,`reporting_team`,`event`,`match`,`scouted_team`) USING BTREE
);